### ISSUE TITLE
Future Planning

### ISSUE THREAD

**Issue by richrd** [richrd/suplemon#161]
To push Suplemon to the next level some core refactoring is needed. 

The main goals are:
- [ ] Support regions (selections) instead of just cursors. This will require refactoring all the multi cursor editing code.
- [ ] Better event system. Now we have input events and global events which might contain input events.  This should be done in a smarter way.
- [ ] Create a better more consistent commands implementation to allow arguments for commands. Also refactor addon modules to behave inline with built in commands.
- [ ] Replace files with views in the main `App` class.
- [x] Support splitting the screen into multiple views horizontally and vertically. This should allow for sidebars too (e.g. for a project or file tree, or in editor help)
- [ ] Refactor App class into smaller components (#55)
- [ ] Try to get some tests implemented (not so straight forward, see #100)
- [ ] Autocomplete: Add keywords for known languages and use them when editing a file in a specific language.
- [ ] Mouse support for making selections if possible.
- [ ] Other things that I didn't think of yet...

Possible enhancements:
- [ ] Multi line promts in favour of #160
- [ ] Code folding
- [ ] A menu at the top that can be navigated to find and use all Suplemon features.

Let me know of any ideas and feedback you might have for implementing these.

**Comment by MrDowntempo** [comment]
Will the 'support regions' portion of this refactoring make code folding possible? That seems like a big important step

**Comment by richrd** [comment]
It doesn't refer to exactly that but code folding would sure be nice to have! It's also something worth taking into account when doing this refactor so thanks for mentioning it. I haven't got any plans for code folding yet but I'll keep it in mind.

**Comment by indolering** [comment]
Macros?
